# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yI450MfbbYaVJiG4qTRpzDjWyJEj-eD2
"""

#Autor: Robert Moor
"""lugar_cita = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
pasos= int(input("digita el numero"))
posicion_cita = lugar_cita.index(pasos)
posicion_hasta = posicion_cita -1

print(f"esto debe recorrer para llegar a maria: {posicion_hasta} cuadras")
"""

fulano = 0

maria = int(input("ingresa el numero de cuadras"))

contador = fulano

while contador < maria:
    print(f"maria esta a: {contador} cuadras de fulano")
    contador += 1